FORMAT: 1A
HOST: https://iWine.apiblueprint.org/

# iWine API 

iWine API allows user to control "smart" decanter and to get it's status with any devices using this API.
API provides few functions:
Authentication: with mobile number (by code)
Authorization: with mobile number (by code)
Change tempreture: changes tempreture in decanter
Shaking decater: 

## API Collection [/api]

### Authentication [/api/auth]
### Signup [/api/signup]

### Signup [POST]
+ Request  (application/json)

{

}
+ Response 200 (application/json)

### Signup_confirm [PUT]

### Change tempreture [/api/tempreture]


### Shake decanter [/api/shake]